steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - README.md
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/$REPO_NAME
    wait_for: ['-']
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/.m2
      - .
    wait_for: ['-']
  - name: gcr.io/$PROJECT_ID/sportbukkit
    args:
      - compile
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -rn
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME
